services:
  ros_dev:
    # Diz ao Compose para construir a imagem a partir do Dockerfile no diretório atual ('.')
    build: .

    container_name: JetsonContainer
    # Mantém o container rodando mesmo que não haja um comando em primeiro plano
    tty: true
    # acesso à GPU NVIDIA
    runtime: nvidia

    # PERMISSÃO TOTAL DE HARDWARE
    privileged: true

    devices:
      # Mapeia o dispositivo da câmera da Jetson para dentro do container
      - "/dev/video0:/dev/video0"

    # pasta de código.
    volumes:
      - ./jetson_ws/src:/root/ros_ws/src
      # Permite a conexão com a tela do seu PC.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/jetson/.Xauthority:/home/jetson/.Xauthority:rw
      # mapeia as portas USB
      - /dev/bus/usb:/dev/bus/usb
      
    # RECOMENDADO: Simplifica muito a rede e a comunicação com a interface gráfica.
    network_mode: "host"
    ipc: "host"
    
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # diz aos programas onde encontrar a chave
      - XAUTHORITY=/home/jetson/.Xauthority